import type { Category, Product, SupplierInfo } from "./types";

export const CATEGORIES: Category[] = [
  { id: "fabrics", nameEn: "Fabrics", nameHi: "कपड़ा", swatch: "sw-fabric" },
  { id: "trims", nameEn: "Trims & accessories", nameHi: "ट्रिम्स और एक्सेसरीज़", swatch: "sw-trim" },
  { id: "packaging", nameEn: "Packaging", nameHi: "पैकेजिंग", swatch: "sw-pack" },
  { id: "jewellery", nameEn: "Jewellery components", nameHi: "ज्वेलरी पुर्जे", swatch: "sw-jewel" },
];

export const SUPPLIERS: Record<string, SupplierInfo> = {
  "sup-surat": {
    id: "sup-surat",
    name: "Surat Textile Works",
    city: "Surat",
    state: "Gujarat",
    verifiedDemo: true,
  },
  "sup-ludhiana": {
    id: "sup-ludhiana",
    name: "Ludhiana Knit Mills",
    city: "Ludhiana",
    state: "Punjab",
    verifiedDemo: true,
  },
  "sup-delhi": {
    id: "sup-delhi",
    name: "Delhi Fabric House",
    city: "Delhi",
    state: "Delhi",
    verifiedDemo: false,
  },
  "sup-tirupur": {
    id: "sup-tirupur",
    name: "Tirupur Trim Co.",
    city: "Tirupur",
    state: "Tamil Nadu",
    verifiedDemo: true,
  },
  "sup-ahmedabad": {
    id: "sup-ahmedabad",
    name: "Ahmedabad Pack Industries",
    city: "Ahmedabad",
    state: "Gujarat",
    verifiedDemo: true,
  },
  "sup-jaipur": {
    id: "sup-jaipur",
    name: "Jaipur Bead Studio",
    city: "Jaipur",
    state: "Rajasthan",
    verifiedDemo: false,
  },
};

export const SELLER = {
  business: "Aarav Apparel",
  owner: "Aarav",
  city: "Delhi",
  address: "Aarav Apparel, Gali No. 7, Gandhi Nagar, Delhi 110031",
  type: "Small apparel manufacturer selling on Meesho",
};

const spec = (key: string, labelEn: string, labelHi: string, value: string) => ({
  key,
  labelEn,
  labelHi,
  value,
});

export const PRODUCTS: Product[] = [
  {
    id: "fab-jersey-black",
    categoryId: "fabrics",
    nameEn: "Cotton single jersey — black",
    nameHi: "कॉटन सिंगल जर्सी — काला",
    unit: "m",
    supplierId: "sup-surat",
    image: "sw-jersey-black",
    specs: [
      spec("composition", "Composition", "कंपोज़िशन", "100% cotton"),
      spec("construction", "Construction", "बुनाई", "Single jersey (knit)"),
      spec("gsm", "GSM", "GSM", "180 GSM"),
      spec("width", "Width", "चौड़ाई", "60 inch"),
      spec("colour", "Colour", "रंग", "Black"),
      spec("finish", "Finish", "फ़िनिश", "Standard finish"),
    ],
    match: {
      material: "cotton jersey",
      colour: "black",
      gsm: 180,
      widthIn: 60,
      construction: "knit",
    },
    buyNow: { unitPricePaise: 10800, deliveryPaise: 40000, minQty: 50, maxQty: 200, leadDays: 5 },
    batchId: "batch-jersey",
    requiresSampleApproval: true,
    localQuotePaise: 12000,
    alternatives: [
      {
        id: "alt-ludhiana",
        supplierId: "sup-ludhiana",
        unitPricePaise: 9200,
        deliveryPaise: 150000,
        leadDays: 14,
        noteEn: "Lowest material price, but high delivery and 14-day lead time.",
        noteHi: "सबसे कम मटीरियल दाम, पर डिलीवरी महँगी और 14 दिन लगेंगे।",
      },
      {
        id: "alt-delhi",
        supplierId: "sup-delhi",
        unitPricePaise: 12000,
        deliveryPaise: 0,
        leadDays: 2,
        noteEn: "Your entered local quote — demo. Fastest, highest delivered price.",
        noteHi: "आपका दर्ज किया लोकल रेट — डेमो। सबसे तेज़, पर सबसे महँगा।",
      },
    ],
  },
  {
    id: "fab-woven-cotton",
    categoryId: "fabrics",
    nameEn: "Woven cotton poplin — off white",
    nameHi: "वोवन कॉटन पॉपलिन — ऑफ़ व्हाइट",
    unit: "m",
    supplierId: "sup-surat",
    image: "sw-woven",
    specs: [
      spec("composition", "Composition", "कंपोज़िशन", "100% cotton"),
      spec("construction", "Construction", "बुनाई", "Poplin (woven)"),
      spec("gsm", "GSM", "GSM", "120 GSM"),
      spec("width", "Width", "चौड़ाई", "44 inch"),
      spec("colour", "Colour", "रंग", "Off white"),
      spec("finish", "Finish", "फ़िनिश", "Mill finish"),
    ],
    match: { material: "woven cotton", colour: "white", gsm: 120, widthIn: 44, construction: "woven" },
    buyNow: { unitPricePaise: 9200, deliveryPaise: 35000, minQty: 50, maxQty: 300, leadDays: 6 },
  },
  {
    id: "fab-poly-lining",
    categoryId: "fabrics",
    nameEn: "Polyester lining — grey",
    nameHi: "पॉलिएस्टर लाइनिंग — ग्रे",
    unit: "m",
    supplierId: "sup-ludhiana",
    image: "sw-lining",
    specs: [
      spec("composition", "Composition", "कंपोज़िशन", "100% polyester"),
      spec("construction", "Construction", "बुनाई", "Taffeta (woven)"),
      spec("gsm", "GSM", "GSM", "70 GSM"),
      spec("width", "Width", "चौड़ाई", "58 inch"),
      spec("colour", "Colour", "रंग", "Grey"),
      spec("finish", "Finish", "फ़िनिश", "Calendered"),
    ],
    match: { material: "polyester lining", colour: "grey", gsm: 70, widthIn: 58, construction: "woven" },
    buyNow: { unitPricePaise: 6400, deliveryPaise: 30000, minQty: 50, maxQty: 400, leadDays: 4 },
    batchId: "batch-lining",
  },
  {
    id: "trim-zipper-8",
    categoryId: "trims",
    nameEn: "Nylon coil zipper 8 inch — black",
    nameHi: "नायलॉन कॉइल ज़िप 8 इंच — काला",
    unit: "pc",
    supplierId: "sup-tirupur",
    image: "sw-zip",
    specs: [
      spec("length", "Length", "लंबाई", "8 inch"),
      spec("material", "Material", "मटीरियल", "Nylon coil, metal pull"),
      spec("colour", "Colour", "रंग", "Black"),
      spec("type", "Type", "प्रकार", "Closed end"),
    ],
    match: { material: "zipper", colour: "black" },
    buyNow: { unitPricePaise: 750, deliveryPaise: 25000, minQty: 100, maxQty: 5000, leadDays: 5 },
  },
  {
    id: "trim-elastic-1",
    categoryId: "trims",
    nameEn: "Knitted elastic 1 inch — white",
    nameHi: "निटेड इलास्टिक 1 इंच — सफ़ेद",
    unit: "m",
    supplierId: "sup-tirupur",
    image: "sw-elastic",
    specs: [
      spec("width", "Width", "चौड़ाई", "1 inch (25 mm)"),
      spec("material", "Material", "मटीरियल", "Polyester / rubber knit"),
      spec("colour", "Colour", "रंग", "White"),
    ],
    match: { material: "elastic", colour: "white" },
    buyNow: { unitPricePaise: 900, deliveryPaise: 25000, minQty: 100, maxQty: 2000, leadDays: 5 },
  },
  {
    id: "trim-thread-cone",
    categoryId: "trims",
    nameEn: "Sewing thread cone 5000 m — black",
    nameHi: "सिलाई धागा कोन 5000 मी — काला",
    unit: "cone",
    supplierId: "sup-tirupur",
    image: "sw-thread",
    specs: [
      spec("length", "Length", "लंबाई", "5000 m per cone"),
      spec("material", "Material", "मटीरियल", "Spun polyester 40/2"),
      spec("colour", "Colour", "रंग", "Black"),
    ],
    match: { material: "thread", colour: "black" },
    buyNow: { unitPricePaise: 6800, deliveryPaise: 20000, minQty: 10, maxQty: 500, leadDays: 4 },
  },
  {
    id: "pack-courier-bag",
    categoryId: "packaging",
    nameEn: "Courier bag 12 × 16 inch",
    nameHi: "कूरियर बैग 12 × 16 इंच",
    unit: "pc",
    supplierId: "sup-ahmedabad",
    image: "sw-bag",
    specs: [
      spec("size", "Size", "साइज़", "12 × 16 inch"),
      spec("thickness", "Thickness", "मोटाई", "60 micron"),
      spec("material", "Material", "मटीरियल", "LDPE, tamper-proof flap"),
      spec("printing", "Printing", "प्रिंटिंग", "Plain (no print)"),
    ],
    match: { material: "courier bag" },
    buyNow: { unitPricePaise: 240, deliveryPaise: 30000, minQty: 200, maxQty: 10000, leadDays: 4 },
    batchId: "batch-bag",
  },
  {
    id: "pack-box-3ply",
    categoryId: "packaging",
    nameEn: "Corrugated box 10 × 8 × 4 inch",
    nameHi: "कोरूगेटेड बॉक्स 10 × 8 × 4 इंच",
    unit: "pc",
    supplierId: "sup-ahmedabad",
    image: "sw-box",
    specs: [
      spec("size", "Size", "साइज़", "10 × 8 × 4 inch"),
      spec("material", "Material", "मटीरियल", "3-ply corrugated kraft"),
      spec("printing", "Printing", "प्रिंटिंग", "Unprinted"),
    ],
    match: { material: "box" },
    buyNow: { unitPricePaise: 1400, deliveryPaise: 40000, minQty: 100, maxQty: 2000, leadDays: 5 },
  },
  {
    id: "pack-label-woven",
    categoryId: "packaging",
    nameEn: "Woven garment label — printed",
    nameHi: "वोवन गारमेंट लेबल — प्रिंटेड",
    unit: "pc",
    supplierId: "sup-ahmedabad",
    image: "sw-label",
    specs: [
      spec("size", "Size", "साइज़", "40 × 20 mm"),
      spec("material", "Material", "मटीरियल", "Woven satin"),
      spec("printing", "Printing", "प्रिंटिंग", "2-colour, your brand name"),
    ],
    match: { material: "label" },
    buyNow: { unitPricePaise: 160, deliveryPaise: 15000, minQty: 500, maxQty: 20000, leadDays: 7 },
  },
  {
    id: "jwl-beads-glass",
    categoryId: "jewellery",
    nameEn: "Glass beads 8 mm — mixed colours",
    nameHi: "काँच के मोती 8 मिमी — मिक्स रंग",
    unit: "pack",
    supplierId: "sup-jaipur",
    image: "sw-beads",
    specs: [
      spec("size", "Size", "साइज़", "8 mm round"),
      spec("material", "Material", "मटीरियल", "Glass"),
      spec("colour", "Colour", "रंग", "Mixed"),
      spec("packsize", "Pack size", "पैक साइज़", "100 g (approx. 180 pcs)"),
    ],
    match: { material: "beads" },
    buyNow: { unitPricePaise: 8500, deliveryPaise: 20000, minQty: 10, maxQty: 500, leadDays: 6 },
  },
  {
    id: "jwl-chain-brass",
    categoryId: "jewellery",
    nameEn: "Brass cable chain — gold tone",
    nameHi: "ब्रास केबल चेन — गोल्ड टोन",
    unit: "m",
    supplierId: "sup-jaipur",
    image: "sw-chain",
    specs: [
      spec("size", "Link size", "लिंक साइज़", "3 × 2 mm"),
      spec("material", "Material", "मटीरियल", "Brass, gold-tone plated"),
      spec("colour", "Colour", "रंग", "Gold tone"),
    ],
    match: { material: "chain" },
    buyNow: { unitPricePaise: 2200, deliveryPaise: 25000, minQty: 50, maxQty: 1000, leadDays: 6 },
  },
  {
    id: "jwl-clasp-lobster",
    categoryId: "jewellery",
    nameEn: "Lobster clasp 12 mm",
    nameHi: "लॉबस्टर क्लैस्प 12 मिमी",
    unit: "pc",
    supplierId: "sup-jaipur",
    image: "sw-clasp",
    specs: [
      spec("size", "Size", "साइज़", "12 mm"),
      spec("material", "Material", "मटीरियल", "Zinc alloy, gold tone"),
      spec("colour", "Colour", "रंग", "Gold tone"),
    ],
    match: { material: "clasp" },
    buyNow: { unitPricePaise: 350, deliveryPaise: 20000, minQty: 100, maxQty: 5000, leadDays: 6 },
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getSupplier(id: string): SupplierInfo {
  return SUPPLIERS[id];
}
