/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as SourcingIndexRouteImport } from './routes/sourcing.index'
import { Route as SourcingRequirementRouteImport } from './routes/sourcing.requirement'
import { Route as SourcingCategoryCategoryIdRouteImport } from './routes/sourcing.category.$categoryId'
import { Route as SourcingProductProductIdRouteImport } from './routes/sourcing.product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingIndexRoute = SourcingIndexRouteImport.update({
  id: '/sourcing/',
  path: '/sourcing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingRequirementRoute = SourcingRequirementRouteImport.update({
  id: '/sourcing/requirement',
  path: '/sourcing/requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingCategoryCategoryIdRoute =
  SourcingCategoryCategoryIdRouteImport.update({
    id: '/sourcing/category/$categoryId',
    path: '/sourcing/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingProductProductIdRoute =
  SourcingProductProductIdRouteImport.update({
    id: '/sourcing/product/$productId',
    path: '/sourcing/product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/sourcing/requirement': typeof SourcingRequirementRoute
  '/orders/': typeof OrdersIndexRoute
  '/sourcing/': typeof SourcingIndexRoute
  '/sourcing/category/$categoryId': typeof SourcingCategoryCategoryIdRoute
  '/sourcing/product/$productId': typeof SourcingProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/sourcing/requirement': typeof SourcingRequirementRoute
  '/orders': typeof OrdersIndexRoute
  '/sourcing': typeof SourcingIndexRoute
  '/sourcing/category/$categoryId': typeof SourcingCategoryCategoryIdRoute
  '/sourcing/product/$productId': typeof SourcingProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/sourcing/requirement': typeof SourcingRequirementRoute
  '/orders/': typeof OrdersIndexRoute
  '/sourcing/': typeof SourcingIndexRoute
  '/sourcing/category/$categoryId': typeof SourcingCategoryCategoryIdRoute
  '/sourcing/product/$productId': typeof SourcingProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/$productId'
    | '/orders/$orderId'
    | '/sourcing/requirement'
    | '/orders/'
    | '/sourcing/'
    | '/sourcing/category/$categoryId'
    | '/sourcing/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/$productId'
    | '/orders/$orderId'
    | '/sourcing/requirement'
    | '/orders'
    | '/sourcing'
    | '/sourcing/category/$categoryId'
    | '/sourcing/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/checkout/$productId'
    | '/orders/$orderId'
    | '/sourcing/requirement'
    | '/orders/'
    | '/sourcing/'
    | '/sourcing/category/$categoryId'
    | '/sourcing/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  SourcingRequirementRoute: typeof SourcingRequirementRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SourcingIndexRoute: typeof SourcingIndexRoute
  SourcingCategoryCategoryIdRoute: typeof SourcingCategoryCategoryIdRoute
  SourcingProductProductIdRoute: typeof SourcingProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/': {
      id: '/sourcing/'
      path: '/sourcing'
      fullPath: '/sourcing/'
      preLoaderRoute: typeof SourcingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/requirement': {
      id: '/sourcing/requirement'
      path: '/sourcing/requirement'
      fullPath: '/sourcing/requirement'
      preLoaderRoute: typeof SourcingRequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/category/$categoryId': {
      id: '/sourcing/category/$categoryId'
      path: '/sourcing/category/$categoryId'
      fullPath: '/sourcing/category/$categoryId'
      preLoaderRoute: typeof SourcingCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/product/$productId': {
      id: '/sourcing/product/$productId'
      path: '/sourcing/product/$productId'
      fullPath: '/sourcing/product/$productId'
      preLoaderRoute: typeof SourcingProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  SourcingRequirementRoute: SourcingRequirementRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SourcingIndexRoute: SourcingIndexRoute,
  SourcingCategoryCategoryIdRoute: SourcingCategoryCategoryIdRoute,
  SourcingProductProductIdRoute: SourcingProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
